env: dev1
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/xiaofd_db?useUnicode=true&characterEncoding=UTF-8&&serverTimezone=UTC
    username: root11
    password: hello123411
security:
  uname: test11
  pwd: test1
