env: dev1
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/xiaofd_db?useUnicode=true&characterEncoding=UTF-8&&serverTimezone=UTC
    username: root
    password: hello12345
security:
  uname: test2
  pwd: qqq1111
